### ISSUE TITLE
Thickness failure in sketches using ellipse, or ellipse arc.

### ISSUE THREAD

**Issue by chopsywa** [realthunder/OCCT#1]
When a sketch contains an ellipse, or ellipse arc with extra detail, such as the attached example, it will pad fine, but thickness fails.

Using Link 2024.01.23
Windows 11 23H2

[ellipse_thickness_fail.zip](https://github.com/realthunder/FreeCAD_assembly3/files/14391147/ellipse_thickness_fail.zip)

**Comment by realthunder** [comment]
The attached file in OP has intersection as corner which fails in OCCT 7.7.2. It works if use circle to replace the ellipse. However, it will fail again if change to arc corner. See [circle.FCStd.zip](https://github.com/realthunder/OCCT/files/14472362/circle.FCStd.zip). It turns out that there are two bugs in OCCT.
