### ISSUE TITLE
[Problem] AdditiveLoft generates invalid geometry (not an issue in mainline 0.21.2)

### ISSUE THREAD

**Issue by mh-dm** [realthunder/OCCT#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 20.04.6 LTS (Unity:Unity7:ubuntu/unity)
Word size of FreeCAD: 64-bit
Version: 2024.409.0.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
[/code]
```

### Subproject(s) affected?

PartDesign

### Problem description

Here's a simple file using an additive loft that's supposed to result in a tube-like shape (remove .zip extension):
[broken-additive-loft.FCStd.zip](https://github.com/user-attachments/files/16615223/broken-additive-loft.FCStd.zip)

This is the invalid geometry:
![broken-addive-loft-geometry](https://github.com/user-attachments/assets/62b1e482-e8f5-462d-ae74-0d5ce74e54aa)

The issue is more clearly seen in a slicer:
![broken-additive-loft](https://github.com/user-attachments/assets/f2f14119-3979-4295-b493-ca5f56276258)

The two sketches used have at least 2 axes of symmetry so the expectation is that the the resulting additive loft geometry keeps said symmetry.

### Anything else?

This issue does not happen if the AdditiveLoft is created in the latest mainline FreeCAD 0.21.2 release.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
What version of mainline FreeCAD are you using. I tried the latest Linux AppImage release and it has the same problem.

**Comment by mh-dm** [comment]
Using this 0.21.2
```
OS: Ubuntu 20.04.6 LTS (Unity:Unity7:ubuntu/unity)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
```

To have it working you just have to reopen the file then delete the AdditiveLoft and recreate it. I'm attaching a working version:
[working-in-21.2-additive-loft.FCStd.zip](https://github.com/user-attachments/files/16637731/working-in-21.2-additive-loft.FCStd.zip)

If you however open this file in Link version it will ask to recompute which will break the geometry.

**Comment by mh-dm** [comment]
The mainline 0.21.2 version I was using was from freecad stable PPA.
```
$ apt info freecad-python3
Package: freecad-python3
Version: 2:0.21.2+dfsg1~202403021917~ubuntu20.04.1
```

To make sure that wasn't a confounding factor, I've downloaded the latest mainline Linux AppImage release and tried it. The behaviour was exactly the same as the 0.21.2 from PPA. It just loads way slower because it's an AppImage and AppImage is bloated and slow. I'm a bit surprised that version info is identical
```
OS: Ubuntu 20.04.6 LTS (Unity:Unity7:ubuntu/unity)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
```

**Comment by realthunder** [comment]
This is most likely a problem of the newer OCCT 7.7. Lastest mainline FreeCAD 0.22 also uses this version which has the same problem. I'll try to find some workaround.

**Comment by realthunder** [comment]
Unfortunately, the problem cannot seem to be fixed on FreeCAD side, which is why I transferred the issue here. What you can do, other than wait for my next release of custom built, is to manually split the circle into four segments, same number as the rectangle. OCCT by right will try evenly split the profiles to make them equal in number. But a recent [commit](https://github.com/Open-Cascade-SAS/OCCT/commit/4607bd0747) adds a condition to keep the split only if the resulting curve is longer than 0.1 of the original one. Before the commit, it is 0.01, much more reasonable IMO.

The below picture illustrates how OCCT auto split the curve. It draws a line from the center of the profile with more segments to each vertex and project it onto the other profile for intersection. The split is done in sequence, and the 0.1 condition is violated in the third split action, causing the unsymmetrical shape you posted. 

1.
![image](https://github.com/user-attachments/assets/c8e97b71-4a20-41a9-90eb-5a944e7857a9)

2.
![image](https://github.com/user-attachments/assets/9769dd13-ee39-4628-9b2d-470afc3d2a74)

3. Violated
![image](https://github.com/user-attachments/assets/07b3ad4d-450d-4611-893d-c3d107a36de1)

4.
![image](https://github.com/user-attachments/assets/36ccb0fc-0267-43d1-b614-65041473eb9a)

The resulting shape is missing one split
![image](https://github.com/user-attachments/assets/b702bb2a-8005-4144-9a98-5e2e7306c5fc)

The correct output
![image](https://github.com/user-attachments/assets/2f2e0dec-d806-4508-9450-a18874285d94)
